import React from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';

import type { CommunityFeedPost } from '../../hooks/useCommunityFeed';
import { colors } from '../../theme';

export default function InteractiveFeedPost({ post, liked, saved, owner, busy, onLike, onSave, onThread, onDelete }: { post: CommunityFeedPost; liked: boolean; saved: boolean; owner: boolean; busy: boolean; onLike: () => void; onSave: () => void; onThread: () => void; onDelete: () => void }) {
  return <View className="border-b border-border py-lg gap-md"><View className="flex-row items-center gap-sm"><View className={`h-[36px] w-[36px] items-center justify-center border ${post.anonymous ? 'bg-white/5 border-white/15' : 'bg-lime/10 border-lime'}`}><Text className={`font-heading-bold text-[11px] ${post.anonymous ? 'text-white/40' : 'text-lime'}`}>{post.author_initials}</Text></View><View className="flex-1"><View className="flex-row items-center gap-sm"><Text className="font-heading-bold text-white text-[14px]">{post.author_name}</Text>{post.anonymous ? <Text className="font-heading-bold text-white/35 text-[9px] uppercase">Anon</Text> : null}</View><Text className="font-body text-white/30 text-[10px] uppercase">{post.author_meta}{formatTime(post.created_at)}</Text></View><View className="bg-lime px-sm py-[2px]"><Text className="font-heading-bold text-dark text-[8px] uppercase">{post.tag}</Text></View>{owner ? <Pressable onPress={() => Alert.alert('Delete post?', 'This post and its replies will be permanently removed.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: onDelete }])} disabled={busy} accessibilityLabel="Delete post"><Feather name="trash-2" size={16} color="#FCA5A5" /></Pressable> : null}</View><Pressable onPress={onThread} accessibilityRole="button" accessibilityLabel={`Open post by ${post.author_name}`} className="active:opacity-75"><Text className="font-body text-white/70 text-[15px] leading-[23px]">{post.content}</Text></Pressable><View className="flex-row items-center gap-xl"><Action icon="heart" label={String(post.likes_count)} active={liked} disabled={busy} onPress={onLike} /><Action icon="message-circle" label={String(post.replies_count)} onPress={onThread} /><Action icon="bookmark" label={saved ? 'Saved' : 'Save'} active={saved} disabled={busy} onPress={onSave} /></View></View>;
}
function Action({ icon, label, active = false, disabled = false, onPress }: { icon: React.ComponentProps<typeof Feather>['name']; label: string; active?: boolean; disabled?: boolean; onPress: () => void }) { return <Pressable onPress={onPress} disabled={disabled} className="min-h-[36px] flex-row items-center gap-xs"><Feather name={icon} size={16} color={active ? colors.lime : colors.tertiaryText} /><Text className={`font-heading-bold text-[10px] uppercase ${active ? 'text-lime' : 'text-white/35'}`}>{label}</Text></Pressable>; }
function formatTime(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }); }
