import React, { useState } from 'react';
import { Image, Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useNavigation, type NavigationProp } from '@react-navigation/native';
import { SafeAreaView } from 'react-native-safe-area-context';

import AppTopBar from '../components/AppTopBar';
import LimeButton from '../components/LimeButton';
import ScreenHero from '../components/mockup/ScreenHero';
import { useAuth } from '../contexts/AuthContext';
import { useDashboard } from '../hooks/useDashboard';
import { type CookTogetherRecipe, useCookTogetherRecipes } from '../hooks/useCookTogetherRecipes';
import type { AppStackParamList } from '../navigation/AppNavigator';
import { colors } from '../theme';

const DIFFICULTIES = [{ value: 'all', label: 'All difficulty' }, { value: 'easy', label: 'Easy' }, { value: 'medium', label: 'Medium' }] as const;
const TIMES = [{ value: 'all', label: 'Any time' }, { value: 15, label: 'Under 15 min' }, { value: 30, label: 'Under 30 min' }, { value: 45, label: 'Under 45 min' }] as const;

export default function CookTogetherScreen() {
  const navigation = useNavigation<NavigationProp<AppStackParamList>>();
  const { user } = useAuth();
  const { refresh: refreshDashboard } = useDashboard(user?.id);
  const recipeData = useCookTogetherRecipes(user?.id);
  const [active, setActive] = useState<CookTogetherRecipe | null>(null);
  const [openFilter, setOpenFilter] = useState<'difficulty' | 'time' | null>(null);
  const [message, setMessage] = useState<string | null>(null);

  const chooseDifficulty = (value: 'all' | 'easy' | 'medium') => { recipeData.setFilters((current) => ({ ...current, difficulty: value })); setOpenFilter(null); };
  const chooseTime = (value: 'all' | number) => { recipeData.setFilters((current) => ({ ...current, maxMins: value })); setOpenFilter(null); };
  const difficultyLabel = DIFFICULTIES.find((item) => item.value === recipeData.filters.difficulty)?.label;
  const timeLabel = TIMES.find((item) => item.value === recipeData.filters.maxMins)?.label;

  return <SafeAreaView edges={['top']} className="flex-1 bg-dark"><ScrollView showsVerticalScrollIndicator={false} contentContainerClassName="px-lg pt-lg pb-xl gap-xl"><AppTopBar leftAccessory={<Pressable onPress={() => navigation.goBack()} accessibilityRole="button" accessibilityLabel="Close Cook Together" className="h-[44px] w-[44px] rounded-full border border-border items-center justify-center"><Feather name="x" size={20} color={colors.text} /></Pressable>} /><ScreenHero eyebrow="Cook together" headline={'Meals that\nmatter'} sub="Kid-friendly recipes that build connection and log active minutes." />
    <View className="flex-row items-center justify-between border-y border-border py-md"><Text className="font-heading-bold text-lime text-[11px] uppercase">Bond score</Text><Text className="font-heading-bold text-lime text-[22px]">{recipeData.bondScore ?? '0'}</Text></View>
    <View className="flex-row gap-lg"><Filter label="Difficulty" value={difficultyLabel ?? 'All difficulty'} open={openFilter === 'difficulty'} onPress={() => setOpenFilter((value) => value === 'difficulty' ? null : 'difficulty')} /><Filter label="Time" value={timeLabel ?? 'Any time'} open={openFilter === 'time'} onPress={() => setOpenFilter((value) => value === 'time' ? null : 'time')} /></View>
    {openFilter === 'difficulty' ? <Options items={DIFFICULTIES} selected={recipeData.filters.difficulty} onSelect={chooseDifficulty} /> : null}
    {openFilter === 'time' ? <Options items={TIMES} selected={recipeData.filters.maxMins} onSelect={chooseTime} /> : null}
    {message ? <Text accessibilityRole="alert" className="font-body text-red-300 text-[13px]">{message}</Text> : null}
    {recipeData.loading ? <View className="gap-sm">{[0,1,2].map((item) => <View key={item} className="h-[220px] rounded-button bg-white/5" />)}</View> : recipeData.error ? <View className="gap-md border-y border-red-400/30 py-lg"><Text className="font-body text-red-300 text-[13px]">{recipeData.error}</Text><LimeButton label="Try again" onPress={() => void recipeData.refresh()} /></View> : recipeData.recipes.length === 0 ? <Text className="font-body text-white/45 text-[14px]">No recipes match those filters yet.</Text> : <View className="gap-md">{recipeData.recipes.map((recipe) => { const saved = recipeData.savedIds.has(recipe.id); const completed = recipeData.completedIds.has(recipe.id); return <View key={recipe.id} className="overflow-hidden rounded-button border border-border bg-card">{recipe.image_url ? <Image source={{ uri: recipe.image_url }} className="h-[180px] w-full" resizeMode="cover" /> : <View className="h-[110px] items-center justify-center bg-lime/5"><Feather name="coffee" size={26} color={colors.lime} /></View>}<View className="p-md gap-md"><View className="flex-row items-start gap-md"><View className="flex-1"><Text className="font-heading-bold text-white text-[19px] uppercase">{recipe.title}</Text><Text className="font-body text-white/45 text-[13px] leading-[19px] mt-xs">{recipe.description ?? 'A simple recipe to cook with your kids.'}</Text></View><Pressable onPress={() => void recipeData.toggleSaved(recipe.id).then((result) => setMessage(result.error))} accessibilityLabel={saved ? 'Unsave recipe' : 'Save recipe'}><Feather name="bookmark" size={21} color={saved ? colors.lime : colors.tertiaryText} /></Pressable></View><View className="flex-row gap-md"><Text className="font-heading-bold text-white/45 text-[11px] uppercase">{recipe.prep_mins} min</Text><Text className="font-heading-bold text-white/45 text-[11px] uppercase">Age {recipe.age_min}+</Text><Text className="font-heading-bold text-lime text-[11px] uppercase">{recipe.difficulty}</Text>{completed ? <Text className="font-heading-bold text-lime text-[11px] uppercase">Done</Text> : null}</View><LimeButton label={completed ? 'Cook again' : 'Start recipe'} onPress={() => { setMessage(null); setActive(recipe); }} /></View></View>; })}</View>}
  </ScrollView><Modal visible={Boolean(active)} animationType="slide" presentationStyle="pageSheet" onRequestClose={() => setActive(null)}><SafeAreaView edges={['top', 'bottom']} className="flex-1 bg-dark"><ScrollView contentContainerClassName="px-lg py-lg gap-xl"><View className="flex-row items-center justify-between"><Text className="font-heading-bold text-lime text-[11px] uppercase">Step by step</Text><Pressable onPress={() => setActive(null)} className="h-[44px] w-[44px] rounded-full border border-border items-center justify-center"><Feather name="x" size={20} color={colors.text} /></Pressable></View><View><Text className="font-heading-bold text-white text-[30px] uppercase">{active?.title}</Text><Text className="font-body text-white/45 text-[13px] mt-xs">{active?.prep_mins} minutes · age {active?.age_min}+ · {active?.difficulty}</Text></View><View><Text className="font-heading-bold text-lime text-[11px] uppercase mb-md">Ingredients</Text>{active?.ingredients.length ? active.ingredients.map((ingredient) => <Text key={ingredient} className="border-b border-border py-sm font-body text-white/65 text-[14px]">{ingredient}</Text>) : <Text className="font-body text-white/45">Ingredients coming soon.</Text>}</View><View className="gap-md">{active?.steps.length ? active.steps.map((step, index) => <View key={`${step.instruction}-${index}`} className="border-l-2 border-l-lime pl-md py-xs"><Text className="font-heading-bold text-lime text-[11px] uppercase">Step {index + 1}</Text>{step.title ? <Text className="font-heading-bold text-white text-[16px] uppercase mt-xs">{step.title}</Text> : null}<Text className="font-body text-white/65 text-[14px] leading-[21px] mt-sm">{step.instruction}</Text>{step.kid_instruction ? <View className="bg-lime/10 border border-lime/20 p-md mt-md"><Text className="font-body text-white text-[13px]"><Text className="font-heading-bold text-lime uppercase">Kid job: </Text>{step.kid_instruction}</Text></View> : null}</View>) : <Text className="font-body text-white/45">Steps coming soon.</Text>}</View>{active ? <LimeButton label={recipeData.completedIds.has(active.id) ? 'Cook again' : 'Mark complete'} loading={recipeData.busyId === active.id} onPress={() => void recipeData.complete(active).then(async (result) => { setMessage(result.error); if (!result.error) { await refreshDashboard(); setActive(null); } })} /> : null}</ScrollView></SafeAreaView></Modal></SafeAreaView>;
}

function Filter({ label, value, open, onPress }: { label: string; value: string; open: boolean; onPress: () => void }) { return <Pressable onPress={onPress} className="flex-1 border-b border-border pb-sm"><Text className="font-heading-bold text-lime text-[9px] uppercase">{label}</Text><View className="flex-row items-center justify-between mt-xs"><Text className="font-body text-white text-[13px]">{value}</Text><Feather name={open ? 'chevron-up' : 'chevron-down'} size={16} color={colors.lime} /></View></Pressable>; }
function Options<T extends string | number>({ items, selected, onSelect }: { items: readonly { value: T; label: string }[]; selected: T; onSelect: (value: T) => void }) { return <View className="border-y border-border">{items.map((item) => <Pressable key={String(item.value)} onPress={() => onSelect(item.value)} className="min-h-[46px] flex-row items-center justify-between border-b border-white/5"><Text className="font-body text-white text-[13px]">{item.label}</Text>{item.value === selected ? <Feather name="check" size={16} color={colors.lime} /> : null}</Pressable>)}</View>; }
